language: go
sudo: false
go:
  - 1.10.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
